version: '3.8'

services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - login-service
      - movie-service
      - auth-service
    networks:
      - marketplace-network

  login-service:
    build: ./login-service
    ports:
      - "5000:5000"
    depends_on:
      - login-database
    networks:
      - marketplace-network

  login-database:
    build: ./login-database
    environment:
      POSTGRES_DB: logindb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - login-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - marketplace-network

  movie-manage-service:
    build: ./art-management-service
    ports:
      - "5001:5001"
    depends_on:
      - art-database
      - redis
    networks:
      - marketplace-network

  movie-service:
    build: ./art-management-service
    depends_on:
      - art-database
      - redis
    deploy:
      replicas: 3
    networks:
      - marketplace-network

  auth-service:
    build: ./login-service
    deploy:
      replicas: 3
    networks:
      - marketplace-network

  art-database:
    build: ./art-database
    environment:
      POSTGRES_DB: artdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - art-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - marketplace-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - marketplace-network

networks:
  marketplace-network:
    driver: bridge

volumes:
  login-db-data:
  art-db-data: